# Generated by Django 3.1.7 on 2021-09-03 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety_ambassador_program', '0003_auto_20210904_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='time_on_site',
        ),
    ]
