# Generated by Django 3.1.7 on 2021-09-05 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety_ambassador_program', '0005_auto_20210905_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digital',
            old_name='name',
            new_name='title',
        ),
    ]
