# Generated by Django 3.1.7 on 2021-09-07 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety_ambassador_program', '0006_auto_20210905_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digital',
            old_name='url',
            new_name='image_url',
        ),
    ]
