# Generated by Django 3.1.7 on 2021-09-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_ambassador_program', '0007_auto_20210907_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digital',
            old_name='image_url',
            new_name='url',
        ),
        migrations.AddField(
            model_name='digital',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
