# Generated by Django 3.1.7 on 2021-09-09 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety_ambassador_program', '0009_digital_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digital',
            name='image_url',
        ),
    ]
