# Generated by Django 3.1.7 on 2021-09-22 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safety_ambassador_program', '0011_auto_20210921_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='digital',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='safety_ambassador_program.grade'),
        ),
    ]
