# Generated by Django 3.1.7 on 2021-09-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_ambassador_program', '0012_digital_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='digital',
            name='intro_completed',
            field=models.BooleanField(default=False),
        ),
    ]
