# Generated by Django 3.1.7 on 2021-10-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_ambassador_program', '0015_auto_20210925_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ('-grade',)},
        ),
        migrations.RemoveField(
            model_name='game',
            name='section',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
