# Generated by Django 3.1.7 on 2021-10-16 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safety_ambassador_program', '0017_auto_20211016_1707'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Responses',
            new_name='Response',
        ),
        migrations.AddField(
            model_name='user',
            name='answers',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='safety_ambassador_program.response'),
        ),
    ]
