# Generated by Django 3.1.7 on 2021-10-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_ambassador_program', '0018_auto_20211016_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='option_selected',
        ),
        migrations.RemoveField(
            model_name='user',
            name='answers',
        ),
        migrations.AddField(
            model_name='response',
            name='a',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='b',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='c',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='d',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='section',
            field=models.CharField(choices=[('Id', 'Identity'), ('Sa', 'Safety'), ('Se', 'Security'), ('We', 'Wellbeing')], default='', max_length=2),
        ),
    ]
