# Generated by Django 3.1.7 on 2021-10-22 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety_ambassador_program', '0020_auto_20211017_2229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
