# Generated by Django 3.1.7 on 2021-10-30 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safety_ambassador_program', '0021_delete_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='safety_ambassador_program.grade'),
        ),
    ]
