# Generated by Django 3.1.7 on 2021-10-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_ambassador_program', '0022_answer_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='grade',
            field=models.CharField(choices=[('P', 'Primary School'), ('M', 'Middle School')], default='', max_length=1, null=True),
        ),
    ]
